package com.apachetune.core.errorreportsystem;

import com.apachetune.core.ResourceManager;

import javax.swing.*;
import java.awt.*;
import java.util.ResourceBundle;

public class ErrorReportDialog extends JDialog {
    private final ResourceBundle resourceBundle =
            ResourceManager.getInstance().getResourceBundle(ErrorReportDialog.class);

    private JPanel contentPane;
    private JTextArea pleaseWaitWhileErrorTextArea;

    public ErrorReportDialog(Component parentComponent) {
        $$$setupUI$$$();
        setContentPane(contentPane);

        setAlwaysOnTop(true);
        setJMenuBar(null);
        setModalityType(ModalityType.TOOLKIT_MODAL);
        setTitle(null);
        setUndecorated(true);

        setSize(400, 60);
        setLocationRelativeTo(parentComponent);

        setModal(true);
    }

    private void createUIComponents() {
        pleaseWaitWhileErrorTextArea = new JTextArea();

        pleaseWaitWhileErrorTextArea.setText(resourceBundle.getString("errorReportDialog.waitMessage"));
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        contentPane = new JPanel();
        contentPane.setLayout(new BorderLayout(0, 0));
        contentPane.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), null));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        contentPane.add(panel1, BorderLayout.CENTER);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        panel1.add(panel2, BorderLayout.WEST);
        final JLabel label1 = new JLabel();
        label1.setIcon(
                new ImageIcon(getClass().getResource("/com/apachetune/core/errorreportsystem/send_error_report.gif")));
        label1.setText("");
        panel2.add(label1, BorderLayout.CENTER);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel1.add(panel3, BorderLayout.CENTER);
        pleaseWaitWhileErrorTextArea.setEditable(false);
        pleaseWaitWhileErrorTextArea.setOpaque(false);
        panel3.add(pleaseWaitWhileErrorTextArea);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}
